### PR TITLE
Examples comparison between Hypothesis and Eris

### PR DESCRIPTION
**Pull request by giorgiosironi**
Feel free to give feedback on coding/writing style, and usage of Jekyll.

### CODE REVIEW

**Comment by DRMacIver** [comment]
Thanks, this looks good!

I have a few questions/comments:
- I tend to use py.test syntax rather than unittest for tests. I'm totally happy for you to use the unittest syntax as it makes the comparison clearer but would appreciate a note mentioning that's why you're doing it
- How do map and bind interact with shrinking in eris? One of the distinguishing features of Hypothesis from classic QuickCheck is that shrinking and generating are integrated, so if I e.g. do integers().map(lambda x: -abs(x)) then I will always get numbers <= 0 even once shrinking has started. Is that also true in Eris? I dimly recall it used not to be the case but maybe I'm misremembering.
- I kinda hate the reversing a list example and try never to use it myself. :-) You can leave it if you really want, but may I suggest "sorting a list twice is the same as sorting it once" as a replacement test example?

**Comment by giorgiosironi** [comment]
On Mon, Aug 29, 2016 at 9:58 AM, David R. MacIver notifications@github.com
wrote:

> Thanks, this looks good!
> 
> I have a few questions/comments:
> - I tend to use py.test syntax rather than unittest for tests. I'm
>   totally happy for you to use the unittest syntax as it makes the comparison
>   clearer but would appreciate a note mentioning that's why you're doing it

 Added, see the new commits.

> - How do map and bind interact with shrinking in eris? One of the
>   distinguishing features of Hypothesis from classic QuickCheck is that
>   shrinking and generating are integrated, so if I e.g. do
>   integers().map(lambda x: -abs(x)) then I will always get numbers <= 0 even
>   once shrinking has started. Is that also true in Eris? I dimly recall it
>   used not to be the case but maybe I'm misremembering.
> 
> I don't remember too in the past :) but it's definitely the case now,
> shrinking is a primitive of the Generator interface that has to be
> respected. Added a comment explaining this.
> - I kinda hate the reversing a list example and try never to use it
>   myself. :-) You can leave it if you really want, but may I suggest "sorting
>   a list twice is the same as sorting it once" as a replacement test example?
> 
> Changed it and added also to the Eris examples. Why hating it by the way?
> Because the inverse function of reverse confusingly happens to be the same
> function, while for encrypt/decrypt would be fine?

## 

Giorgio Sironi (@giorgiosironi)
http://giorgiosironi.com http://giorgiosironi.blogspot.com/

**Comment by DRMacIver** [comment]
Thanks, this looks good! I'm happy to click merge if you're happy for me to.

> I don't remember too in the past :) but it's definitely the case now,
> shrinking is a primitive of the Generator interface that has to be
> respected. Added a comment explaining this.

Cool. We should talk at some point about how this works in Eris - I had a quick poke at the code and it _looks_ like it's similar to how things worked in Hypothesis < 3.0, but I'm not 100% sure.

> Why hating it by the way?

It's mostly because it's a boring example. There are no interesting ways for the code to be wrong, which makes it very artificial, but it gets repeated everywhere. I'm OK with the commutative one because it's so obviously a hello world, but reversing just seems like it should be a real example and isn't.

**Comment by giorgiosironi** [comment]
On Sun, Sep 4, 2016 at 2:45 PM, David R. MacIver notifications@github.com
wrote:

> Thanks, this looks good! I'm happy to click merge if you're happy for me
> to.

+1 from me

I don't remember too in the past :) but it's definitely the case now,

> shrinking is a primitive of the Generator interface that has to be
> respected. Added a comment explaining this.
> 
> Cool. We should talk at some point about how this works in Eris - I had a
> quick poke at the code and it _looks_ like it's similar to how things
> worked in Hypothesis < 3.0, but I'm not 100% sure.

I hope to stabilize it first, since I am following your old suggestions to
go for O(log n) shrinking time rather than O(n), but lots of Generators
need to be updated now that Eris supports that.

## 

Giorgio Sironi (@giorgiosironi)
http://giorgiosironi.com http://giorgiosironi.blogspot.com/

**Comment by DRMacIver** [comment]
Hmm. Looks like there are a few publishing problems with it that I didn't catch, sorry!. I'll just quickly fix those up.

**Pull request merged**
