### PR TITLE
General cleanup, elimination of raw HTML landing page, rewording of Training, Services sections

### PR DESCRIPTION
**Pull request by wk**
- Standardized file naming: training/index.markdown -> training/index.md
- Converted landing page (index.html) to markdown: index.html -> index.md
- Eliminated landing page-specific CSS, applying landing page CSS to standard page layout instead
- Reworded Services and Support section, providing more comprehensive introduction text and adding reference to distance education and consulting options. This can be considered a business feature request (BFR) resulting from a narrow focus group (p=4) which identified a trend in organizations where some development resources are outsourced and operate from a different physical location than the company's headquarters and project management staff. This could mean that the cost of flights and accommodation for getting the team together in a single physical location vastly exceeds the cost of the training provider for a specific support tool.
- Reworded and restructured Training page making several references to availability of distance education for distributed development teams, this is part of the aforementioned BFR.

### CODE REVIEW

**Comment by wk** [comment]
I am assigning copyright to any of these changes to the original author in exchange for no consideration.

**Comment by DRMacIver** [comment]
Wow! Thanks for this. I didn't actually expect people to make pull requests on this repo, but I'm very glad you did. :-)

I'm finding it a bit hard to evaluate both formatting and content change at the same time, so rather than just click merge I'm going to cherry-pick your purely formatting changes into master initially and then have a look at the copy changes. I _think_ the copy changes are all good, but they sortof commit me to things that I've not really thought about, so I'd like to give some more thought. The formatting changes OTOH are just unambiguously good.

**Comment by DRMacIver** [comment]
Or rather not cherry-pick, but instead I've just merged up to 0348d7e

**Comment by DRMacIver** [comment]
OK. Generally looks good. Thanks again for this!

**Pull request merged**
